### ISSUE TITLE
400 error when attempting to buy coins

### ISSUE THREAD

**Issue by cheng21tang** [cheng21tang/Project-3#194]
new user created account

**Comment by Dylancouzon** [comment]
Looking at it.

**Comment by Dylancouzon** [comment]
@cheng21tang  I can't Replicate the issue.
Is your blockchain/chain.json present?

![image](https://user-images.githubusercontent.com/80007470/120707855-ad218080-c46f-11eb-8e5b-d34d6e6e76d0.png)

**Comment by Dylancouzon** [comment]
Cause >> Amount too small.
We need to interpret Stripe error message.
