### ISSUE TITLE
Signup with google fail to create sessions

### ISSUE THREAD

**Issue by Dylancouzon** [cheng21tang/Project-3#231]

**Comment by Dylancouzon** [comment]
@cheng21tang 
I can't reproduce the bug.
Can you do a fresh pull and let me know if it is still present?

**Comment by cheng21tang** [comment]
I repulled from Main, did a fresh seed and npm install and I'm no longer seeing this issue with Sign-Up or Login after I signed up with google. Closing this issue as edge-case and we can reopen a ticket if we get other reports.
